
all: p1 p2 p3 p4 p2_more

clean:
	rm -f p1 p2 p3 p4 p2_more

p1: p1.c
	gcc -o p1 p1.c -Wall

p2: p2.c
	gcc -o p2 p2.c -Wall

p3: p3.c
	gcc -o p3 p3.c -Wall

p4: p4.c
	gcc -o p4 p4.c -Wall

p2_more: p2_more.c
	gcc -o p2_more p2_more.c -Wall
